### ISSUE TITLE
Diagnostic highlight not cleared properly

### ISSUE THREAD

**Issue by ls4154** [prabirshrestha/vim-lsp#1135] opened 2021-04-06 14:09 UTC
Since I updated vim-lsp a few weeks ago, diagnostic highlights are not erased properly, even after I fixed errors. This happens randomly but quite often.  In the bottom line of the screenshot, the warning and error highlights are not cleared.

![Screenshot from 2021-04-06 22-49-23](https://user-images.githubusercontent.com/26355219/113723893-c2f31d80-972c-11eb-8205-90f34954621c.png)

**Environment**
OS: Ubuntu 20.10
vim version: 8.2.2539
Langserver: clangd
Plugins: asyncomplete.vim, async.vim, vim-lsp, asyncomplete-lsp.vim

I found reverting commit 627dab0 fixed it.

**Comment by prabirshrestha** [comment] 2021-04-13 22:11
dupe of https://github.com/prabirshrestha/vim-lsp/issues/1142

**Closed by prabirshrestha** 2021-04-13 22:11 UTC
