### ISSUE TITLE
code actions and formatting document results deleting the function from the file instead of formatting for typescriptreact files

### ISSUE THREAD

**Issue by NikosEfthias** [prabirshrestha/vim-lsp#768] opened 2020-03-25 23:29 UTC

**Comment by hrsh7th** [comment] 2020-03-26 03:35
Could you provide the repro steps?

**Comment by NikosEfthias** [comment] 2020-03-26 04:18
- create a new ts file
- add the following snippet
```
interface Foo{
    bar?:string
}
```
- execute `:LspDocumentFormat`
- interface gets deleted

Additionally if interface is defined on a single line things work just fine
```
interface Foo{bar?:string} //work fine
```
gif below shows the problem

![saving](https://user-images.githubusercontent.com/9097437/77609739-43881700-6f3a-11ea-85f5-e88182ac5578.gif)

**Comment by hrsh7th** [comment] 2020-03-26 04:37
It's strange...

In my environment, the problem seems does not reproduce.
Could you tell me the more infomartion?

- `:LspStatus` results
- your vimrc settings

![vim-lsp-not-repro](https://user-images.githubusercontent.com/629908/77610697-c7f08f00-6f66-11ea-966e-e0d669fae20b.gif)

**Comment by NikosEfthias** [comment] 2020-03-26 10:08
lsp status only reports typescript language server
![image](https://user-images.githubusercontent.com/9097437/77634863-1c960900-6f6b-11ea-94fe-12fca09011e8.png)
I will comment out all the plugins except lsp and try again if issue still happens I will send you a minimal vimrc

**Comment by NikosEfthias** [comment] 2020-03-26 10:29
with a minimal vimrc containing just the following lines 
```
source ~/.config/nvim/autoload/plug.vim
call plug#begin("/tmp/plugs")
Plug 'prabirshrestha/async.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
call plug#end()
au BufReadPost *.ts set ft=typescript

```
I also cant seem to reproduce the problem. Do you have any suggestions on identifying the source of the issue.

**Comment by hrsh7th** [comment] 2020-03-26 10:35
Sorry, I don't well english.

Is your mean can't reproduced the problem with minimal vimrc?

Needs debug log for more deep investigate it.

Could you tell me a debug log?

1. `let g:lsp_log_file = '/tmp/lsp.log'`
2. Do reproduce steps
3. `cat /tmp/lsp.log`

**Comment by NikosEfthias** [comment] 2020-03-26 10:56
here are the logs. Does it make any sense ? 
```
Thu 26 Mar 2020 02:53:51 PM +04:["s:on_text_document_did_change()", 1]
Thu 26 Mar 2020 02:53:51 PM +04:["s:send_didchange_queue() will be triggered"]
Thu 26 Mar 2020 02:53:53 PM +04:["s:on_text_document_did_save()", 1]
Thu 26 Mar 2020 02:53:53 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "server already started"}}]
Thu 26 Mar 2020 02:53:53 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "jsonrpc": "2.0", "result": {"capabilities": {"executeCommandProvider": {"commands": ["_typescript.applyWorkspaceEdit", "_typescript.applyCodeAction", "_typescript.applyRefactoring", "_typescript.organizeImports", "_typescript.applyRenameFile"]}, "documentHighlightProvider": true, "hoverProvider": true, "typeDefinitionProvider": true, "definitionProvider": true, "referencesProvider": true, "signatureHelpProvider": {"triggerCharacters": ["(", ",", "<"]}, "foldingRangeProvider": true, "codeActionProvider": true, "textDocumentSync": 2, "callsProvider": true, "implementationProvider": true, "workspaceSymbolProvider": true, "documentFormattingProvider": true, "documentSymbolProvider": true, "renameProvider": true, "completionProvider": {"resolveProvider": true, "triggerCharacters": [".", "\"", "'", "/", "@", "<"]}}}}, "server_name": "typescript-language-server"}, "message": "lsp server already initialized"}}]
Thu 26 Mar 2020 02:53:53 PM +04:["--->", 8, "typescript-language-server", {"method": "workspace/didChangeConfiguration", "params": {"settings": {}}}]
Thu 26 Mar 2020 02:53:53 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "configuration sent"}}]
Thu 26 Mar 2020 02:53:53 PM +04:[{"response": {"data": {"path": "file:///tmp/example.ts", "__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "already opened"}}]
Thu 26 Mar 2020 02:53:53 PM +04:["s:update_file_content()", 1]
Thu 26 Mar 2020 02:53:53 PM +04:["--->", 8, "typescript-language-server", {"method": "textDocument/didChange", "params": {"contentChanges": [{"range": {"end": {"character": 0, "line": 0}, "start": {"character": 0, "line": 0}}, "text": "interface Foo{\n\tbar?:string\n}", "rangeLength": 0}], "textDocument": {"uri": "file:///tmp/example.ts", "version": 10}}}]
Thu 26 Mar 2020 02:53:53 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "server already started"}}]
Thu 26 Mar 2020 02:53:53 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "jsonrpc": "2.0", "result": {"capabilities": {"executeCommandProvider": {"commands": ["_typescript.applyWorkspaceEdit", "_typescript.applyCodeAction", "_typescript.applyRefactoring", "_typescript.organizeImports", "_typescript.applyRenameFile"]}, "documentHighlightProvider": true, "hoverProvider": true, "typeDefinitionProvider": true, "definitionProvider": true, "referencesProvider": true, "signatureHelpProvider": {"triggerCharacters": ["(", ",", "<"]}, "foldingRangeProvider": true, "codeActionProvider": true, "textDocumentSync": 2, "callsProvider": true, "implementationProvider": true, "workspaceSymbolProvider": true, "documentFormattingProvider": true, "documentSymbolProvider": true, "renameProvider": true, "completionProvider": {"resolveProvider": true, "triggerCharacters": [".", "\"", "'", "/", "@", "<"]}}}}, "server_name": "typescript-language-server"}, "message": "lsp server already initialized"}}]
Thu 26 Mar 2020 02:53:53 PM +04:["--->", 8, "typescript-language-server", {"method": "workspace/didChangeConfiguration", "params": {"settings": {}}}]
Thu 26 Mar 2020 02:53:53 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "configuration sent"}}]
Thu 26 Mar 2020 02:53:53 PM +04:[{"response": {"data": {"path": "file:///tmp/example.ts", "__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "already opened"}}]
Thu 26 Mar 2020 02:53:53 PM +04:[{"response": {"data": {"path": "file:///tmp/example.ts", "__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "not dirty"}}]
Thu 26 Mar 2020 02:53:53 PM +04:["--->", 8, "typescript-language-server", {"method": "textDocument/foldingRange", "on_notification": "---funcref---", "bufnr": 1, "params": {"textDocument": {"uri": "file:///tmp/example.ts"}}, "sync": 0}]
Thu 26 Mar 2020 02:53:53 PM +04:[{"response": {"data": {"path": "file:///tmp/example.ts", "__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "textDocument/didChange sent"}}]
Thu 26 Mar 2020 02:53:53 PM +04:["s:update_file_content()", 1]
Thu 26 Mar 2020 02:53:53 PM +04:["--->", 8, "typescript-language-server", {"method": "textDocument/didSave", "params": {"textDocument": {"uri": "file:///tmp/example.ts"}}}]
Thu 26 Mar 2020 02:53:53 PM +04:[{"response": {"data": {"path": "file:///tmp/example.ts", "__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "textDocument/didSave sent"}}]
Thu 26 Mar 2020 02:53:53 PM +04:["<---", 8, "typescript-language-server", {"response": {"id": 16, "jsonrpc": "2.0", "result": [{"startLine": 0, "endLine": 1}]}, "request": {"id": 16, "jsonrpc": "2.0", "method": "textDocument/foldingRange", "params": {"textDocument": {"uri": "file:///tmp/example.ts"}}}}]
Thu 26 Mar 2020 02:53:53 PM +04:["<---", 8, "typescript-language-server", {"response": {"method": "textDocument/publishDiagnostics", "jsonrpc": "2.0", "params": {"uri": "file:///tmp/example.ts", "diagnostics": []}}}]
Thu 26 Mar 2020 02:53:55 PM +04:["s:send_event_queue()"]
Thu 26 Mar 2020 02:53:55 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "server already started"}}]
Thu 26 Mar 2020 02:53:55 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "jsonrpc": "2.0", "result": {"capabilities": {"executeCommandProvider": {"commands": ["_typescript.applyWorkspaceEdit", "_typescript.applyCodeAction", "_typescript.applyRefactoring", "_typescript.organizeImports", "_typescript.applyRenameFile"]}, "documentHighlightProvider": true, "hoverProvider": true, "typeDefinitionProvider": true, "definitionProvider": true, "referencesProvider": true, "signatureHelpProvider": {"triggerCharacters": ["(", ",", "<"]}, "foldingRangeProvider": true, "codeActionProvider": true, "textDocumentSync": 2, "callsProvider": true, "implementationProvider": true, "workspaceSymbolProvider": true, "documentFormattingProvider": true, "documentSymbolProvider": true, "renameProvider": true, "completionProvider": {"resolveProvider": true, "triggerCharacters": [".", "\"", "'", "/", "@", "<"]}}}}, "server_name": "typescript-language-server"}, "message": "lsp server already initialized"}}]
Thu 26 Mar 2020 02:53:55 PM +04:["--->", 8, "typescript-language-server", {"method": "workspace/didChangeConfiguration", "params": {"settings": {}}}]
Thu 26 Mar 2020 02:53:55 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "configuration sent"}}]
Thu 26 Mar 2020 02:53:55 PM +04:[{"response": {"data": {"path": "file:///tmp/example.ts", "__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "already opened"}}]
Thu 26 Mar 2020 02:53:55 PM +04:[{"response": {"data": {"path": "file:///tmp/example.ts", "__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "not dirty"}}]
Thu 26 Mar 2020 02:53:56 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "server already started"}}]
Thu 26 Mar 2020 02:53:56 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "jsonrpc": "2.0", "result": {"capabilities": {"executeCommandProvider": {"commands": ["_typescript.applyWorkspaceEdit", "_typescript.applyCodeAction", "_typescript.applyRefactoring", "_typescript.organizeImports", "_typescript.applyRenameFile"]}, "documentHighlightProvider": true, "hoverProvider": true, "typeDefinitionProvider": true, "definitionProvider": true, "referencesProvider": true, "signatureHelpProvider": {"triggerCharacters": ["(", ",", "<"]}, "foldingRangeProvider": true, "codeActionProvider": true, "textDocumentSync": 2, "callsProvider": true, "implementationProvider": true, "workspaceSymbolProvider": true, "documentFormattingProvider": true, "documentSymbolProvider": true, "renameProvider": true, "completionProvider": {"resolveProvider": true, "triggerCharacters": [".", "\"", "'", "/", "@", "<"]}}}}, "server_name": "typescript-language-server"}, "message": "lsp server already initialized"}}]
Thu 26 Mar 2020 02:53:56 PM +04:["--->", 8, "typescript-language-server", {"method": "workspace/didChangeConfiguration", "params": {"settings": {}}}]
Thu 26 Mar 2020 02:53:56 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "configuration sent"}}]
Thu 26 Mar 2020 02:53:56 PM +04:[{"response": {"data": {"path": "file:///tmp/example.ts", "__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "already opened"}}]
Thu 26 Mar 2020 02:53:56 PM +04:[{"response": {"data": {"path": "file:///tmp/example.ts", "__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "not dirty"}}]
Thu 26 Mar 2020 02:53:56 PM +04:["--->", 8, "typescript-language-server", {"method": "textDocument/formatting", "on_notification": "---funcref---", "sync": 0, "params": {"options": {"insertSpaces": false, "tabSize": 4}, "textDocument": {"uri": "file:///tmp/example.ts"}}}]
Thu 26 Mar 2020 02:53:56 PM +04:["<---", 8, "typescript-language-server", {"response": {"id": 17, "jsonrpc": "2.0", "result": [{"range": {"end": {"character": 13, "line": 0}, "start": {"character": 13, "line": 0}}, "newText": " "}, {"range": {"end": {"character": 6, "line": 1}, "start": {"character": 6, "line": 1}}, "newText": " "}]}, "request": {"id": 17, "jsonrpc": "2.0", "method": "textDocument/formatting", "params": {"options": {"insertSpaces": false, "tabSize": 4}, "textDocument": {"uri": "file:///tmp/example.ts"}}}}]
Thu 26 Mar 2020 02:53:56 PM +04:["s:on_text_document_did_change()", 1]
Thu 26 Mar 2020 02:53:56 PM +04:["s:send_didchange_queue() will be triggered"]
Thu 26 Mar 2020 02:54:00 PM +04:["s:send_event_queue()"]
Thu 26 Mar 2020 02:54:00 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "server already started"}}]
Thu 26 Mar 2020 02:54:00 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "jsonrpc": "2.0", "result": {"capabilities": {"executeCommandProvider": {"commands": ["_typescript.applyWorkspaceEdit", "_typescript.applyCodeAction", "_typescript.applyRefactoring", "_typescript.organizeImports", "_typescript.applyRenameFile"]}, "documentHighlightProvider": true, "hoverProvider": true, "typeDefinitionProvider": true, "definitionProvider": true, "referencesProvider": true, "signatureHelpProvider": {"triggerCharacters": ["(", ",", "<"]}, "foldingRangeProvider": true, "codeActionProvider": true, "textDocumentSync": 2, "callsProvider": true, "implementationProvider": true, "workspaceSymbolProvider": true, "documentFormattingProvider": true, "documentSymbolProvider": true, "renameProvider": true, "completionProvider": {"resolveProvider": true, "triggerCharacters": [".", "\"", "'", "/", "@", "<"]}}}}, "server_name": "typescript-language-server"}, "message": "lsp server already initialized"}}]
Thu 26 Mar 2020 02:54:00 PM +04:["--->", 8, "typescript-language-server", {"method": "workspace/didChangeConfiguration", "params": {"settings": {}}}]
Thu 26 Mar 2020 02:54:00 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "configuration sent"}}]
Thu 26 Mar 2020 02:54:00 PM +04:[{"response": {"data": {"path": "file:///tmp/example.ts", "__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "already opened"}}]
Thu 26 Mar 2020 02:54:00 PM +04:["s:update_file_content()", 1]
Thu 26 Mar 2020 02:54:00 PM +04:["--->", 8, "typescript-language-server", {"method": "textDocument/didChange", "params": {"contentChanges": [{"range": {"end": {"character": 1, "line": 2}, "start": {"character": 0, "line": 0}}, "text": "", "rangeLength": 29}], "textDocument": {"uri": "file:///tmp/example.ts", "version": 11}}}]
Thu 26 Mar 2020 02:54:00 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "server already started"}}]
Thu 26 Mar 2020 02:54:00 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "init_result": {"id": 1, "jsonrpc": "2.0", "result": {"capabilities": {"executeCommandProvider": {"commands": ["_typescript.applyWorkspaceEdit", "_typescript.applyCodeAction", "_typescript.applyRefactoring", "_typescript.organizeImports", "_typescript.applyRenameFile"]}, "documentHighlightProvider": true, "hoverProvider": true, "typeDefinitionProvider": true, "definitionProvider": true, "referencesProvider": true, "signatureHelpProvider": {"triggerCharacters": ["(", ",", "<"]}, "foldingRangeProvider": true, "codeActionProvider": true, "textDocumentSync": 2, "callsProvider": true, "implementationProvider": true, "workspaceSymbolProvider": true, "documentFormattingProvider": true, "documentSymbolProvider": true, "renameProvider": true, "completionProvider": {"resolveProvider": true, "triggerCharacters": [".", "\"", "'", "/", "@", "<"]}}}}, "server_name": "typescript-language-server"}, "message": "lsp server already initialized"}}]
Thu 26 Mar 2020 02:54:00 PM +04:["--->", 8, "typescript-language-server", {"method": "workspace/didChangeConfiguration", "params": {"settings": {}}}]
Thu 26 Mar 2020 02:54:00 PM +04:[{"response": {"data": {"__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "configuration sent"}}]
Thu 26 Mar 2020 02:54:00 PM +04:[{"response": {"data": {"path": "file:///tmp/example.ts", "__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "already opened"}}]
Thu 26 Mar 2020 02:54:00 PM +04:[{"response": {"data": {"path": "file:///tmp/example.ts", "__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "not dirty"}}]
Thu 26 Mar 2020 02:54:00 PM +04:["--->", 8, "typescript-language-server", {"method": "textDocument/foldingRange", "on_notification": "---funcref---", "bufnr": 1, "params": {"textDocument": {"uri": "file:///tmp/example.ts"}}, "sync": 0}]
Thu 26 Mar 2020 02:54:00 PM +04:[{"response": {"data": {"path": "file:///tmp/example.ts", "__data__": "vim-lsp", "server_name": "typescript-language-server"}, "message": "textDocument/didChange sent"}}]
Thu 26 Mar 2020 02:54:00 PM +04:["<---", 8, "typescript-language-server", {"response": {"id": 18, "jsonrpc": "2.0", "result": []}, "request": {"id": 18, "jsonrpc": "2.0", "method": "textDocument/foldingRange", "params": {"textDocument": {"uri": "file:///tmp/example.ts"}}}}]
Thu 26 Mar 2020 02:54:00 PM +04:["<---", 8, "typescript-language-server", {"response": {"method": "textDocument/publishDiagnostics", "jsonrpc": "2.0", "params": {"uri": "file:///tmp/example.ts", "diagnostics": []}}}]
Thu 26 Mar 2020 02:54:04 PM +04:["s:on_text_document_did_close()", 1]
Thu 26 Mar 2020 02:54:04 PM +04:["s:on_exit", 8, "typescript-language-server", "exited", 0]

```

**Comment by NikosEfthias** [comment] 2020-03-26 11:00
not it started deleting the field :D 
![Peek 2020-03-26 14-59](https://user-images.githubusercontent.com/9097437/77639679-8bc32b80-6f72-11ea-934b-0505154bcc11.gif)

**Comment by NikosEfthias** [comment] 2020-03-26 11:09
now it started to delete the field :D 
![Peek 2020-03-26 15-06](https://user-images.githubusercontent.com/9097437/77640390-bb266800-6f73-11ea-9665-cbaaae643905.gif)

**Comment by hrsh7th** [comment] 2020-03-26 11:15
If minimal vimrc does not reproduce the problem, you should provide reproducible full vimrc.

The `textDocument/formatting` seems return the right textEdits.
```
{"range": {"end": {"character": 13, "line": 0}, "start": {"character": 13, "line": 0}}, "newText": " "}, {"range": {"end": {"character": 6, "line": 1}, "start": {"character": 6, "line": 1}}, "newText": " "}]}
```

I can't understand the reason now...

**Comment by NikosEfthias** [comment] 2020-03-28 15:50
@hrsh7th seems this is happening when `backupcopy` option is set to `yes` in neovim

**Comment by NikosEfthias** [comment] 2020-03-29 17:36
finally I figured it out!!!
the issue apparently was caused by folding when lines are folded seems vimlsp cannot figure out where and how to format

**Comment by aravind2612krishna** [comment] 2020-04-06 05:38
I've heard of similar tales of lines of code getting deleted for cpp files near folds, when RangeFormat was invoked.

**Comment by hrsh7th** [comment] 2020-04-12 06:59
Thanks for reporting.
Sorry for my delay.

I've reproduced the problem.
I will fix it.

**Comment by hrsh7th** [comment] 2020-04-12 15:28
@NikosEfthias 
I sent PR to this issue.
Could you test with #788?

**Comment by NikosEfthias** [comment] 2020-04-14 08:27
Sure I will be pulling the version shortly today

**Comment by NikosEfthias** [comment] 2020-04-15 19:16
@hrsh7th I pulled that particular branch so far things seem to be working smoothly but I will be testing more thoroughly and let you know if any issues occur so far it seems the issue has been fixed

**Comment by prabirshrestha** [comment] 2020-04-19 17:23
https://github.com/prabirshrestha/vim-lsp/pull/788 has been merged to master. Thanks for the bug report and the fixes.

**Closed by prabirshrestha** 2020-04-19 17:23 UTC
Labels: bug
