### ISSUE TITLE
vim-lsp 2021 (poll)

### ISSUE THREAD

**Issue by prabirshrestha** [prabirshrestha/vim-lsp#1020] opened 2021-01-05 06:02 UTC
Last year when I did [vim-lsp 2020](https://github.com/prabirshrestha/vim-lsp/issues/624) I was able to share my vision and have others provide feedback and we were able to make good progress on features that were requested by users. This year I want to try something different. Instead of me providing on what I want to work on I want to see what you would like to see in vim-lsp. This is similar concept to what vim has done in the past - https://github.com/vim/vim/issues/3573.

**Please use one comment for each suggestion. Use the thumbs-up and thumbs-down to express whether you agree with a specific answer/request (you can find that in the header of the comment on the top right, looks like a smiley face).**

Comments can be related to a new feature, bug fixes, performance improvements related to [vim-lsp](https://github.com/prabirshrestha/vim-lsp) or [vim-lsp-settings](https://github.com/mattn/vim-lsp-settings). I have tons of  awesome new ideas I would like to add in vim-lsp as well as vim-lsp-settings but would like to hear your feedback first.

**Please try to provide feedback by Jan 15th 2021.**

**Comment by timsofteng** [comment] 2021-01-05 09:35
I think responsibility and efficient should be primary goals. I've tried built-in neovim-lsp and it's really fast and it use less resources (cpu, ram) of pc than other lsps for vim and nvim. I suppose vim-lsp should be as quick and and lite as neovim-lsp or even better. Otherwise people will just choose neovim-lsp. So in my opinion you should start to adapt vim-lsp to new vim9 which I suppose will be released soon. We already have blazing fast lsp for neovim but for vim we doesn't. That's why I suggest you to consider new vim9.

Thanks.

**Comment by edganiukov** [comment] 2021-01-05 12:08
I would like to have an opportunity to customize `workspace_config` per project (e.g. via config file in root directory). I know vim-lsp-settings has this feature, but I prefer to install and configure LSP server in my own.

**Comment by prabirshrestha** [comment] 2021-01-11 03:36
I have explicitly opened a new issue asking details on perf and what you would like to see. Please feel free to reply in details at https://github.com/prabirshrestha/vim-lsp/issues/1037 so i can work on those specific fixes.

**Comment by juanibiapina** [comment] 2021-01-12 12:06
`lsp_document_highlight_enabled` should not be enabled by default.

**Comment by astifter** [comment] 2021-02-19 06:13
Hi, thanks for all the work. I have tried nvim-lsp may times now and I always switch back to vim-lsp for various reasons. 

I'm using it mainly with clangd on C/C++ codebase with 6k5 files and 144kloc and it works marvelous.

I have one small issue with autowrite and autowriteall, I'll open a separate issue for that.

**Comment by idbrii** [comment] 2021-06-08 18:39
I'd love to see a focus on stability including for issues to stay open longer than 2 months.

Would be great if stalebot labeled with 'requires-retest' after 2 months with a request to test on the latest version, and close if the user doesn't respond within 6 months. Rephrasing as "please ensure this occurs on latest" and closing because the user didn't retest would remove the discouraging feeling of having your issues marked wontfix.

There's issues like #1087 where after effort put into fixing an issue it gets closed automatically. Maybe there's something wrong with stalebot since labelled that one and closed it on the same day, but did the expected behaviour on this issue?

**Closed** 2021-08-17 01:57 UTC
Labels: wontfix

**Comment by prabirshrestha** [comment] 2022-01-02 20:51
Now that 2021 is over please go over [2022 posts](https://github.com/prabirshrestha/vim-lsp/discussions/1255).
