### ISSUE TITLE
Neovim gets stuck for ~6min after opening a cpp file - most of the time is spent in vim-lsp code

### ISSUE THREAD

**Issue by jbarik** [prabirshrestha/vim-lsp#1073] opened 2021-02-24 09:32 UTC
I work on a very large code base(using ccls as lsp server). On opening a cpp file neovim gets stuck for almost 6 minutes before it becomes normal. On turning on the profiler, I see that most of the time is spent in 

on_stdout : vim-lsp/autoload/lsp/client.vim:33 (423 sec)
makeSubjectFactory: vim-lsp/autoload/lsp/callbag.vim:64 (31 sec)

[nvim_profile.log](https://github.com/prabirshrestha/vim-lsp/files/6034838/nvim_profile.log)

Please let me know if I need to provide more info.

**Comment by prabirshrestha** [comment] 2021-02-26 21:48
you seem to have log enabled. can you disable it. logging makes vim-lsp very slow.

```
FUNCTION  lsp#log_verbose()
    Defined: ~/.config/nvim/pack/packager/start/vim-lsp/autoload/lsp.vim:37
Called 47005 times
Total time:   0.795089
 Self time:   0.475382

count  total (s)   self (s)
47005              0.061216     if g:lsp_log_verbose
47005   0.685727   0.366020         call call(function('lsp#log'), a:000)
47005              0.020960     endif
```

please also attach vim-lsp logs if possible. feel free to remove file contents out of it before publishing.

```
FUNCTION  lsp#stream()
    Defined: ~/.config/nvim/pack/packager/start/vim-lsp/autoload/lsp.vim:980
Called 46979 times
Total time:  57.324223
 Self time:   0.597850

count  total (s)   self (s)
46979              0.051216     if a:0 == 0
                                    return lsp#callbag#share(s:Stream)
46979              0.023112     else
46979  57.113824   0.389958         call s:Stream(a:1, a:2)
46979              0.018364     endif
```

Something is taking to long time to process the stream.

how big is your file is size in kb and total lines or chars.

LSP client parsing also seems slow. This is one of the place where I have wanted to optimize but had seen any real logs for it yet. 
@hrsh7th it will be good to see if your lsp client has similar issues. 

```
FUNCTION  <SNR>112_send_request()
    Defined: ~/.config/nvim/pack/packager/start/vim-lsp/autoload/lsp.vim:732
Called 1 time
Total time:   0.000547
 Self time:   0.000058

count  total (s)   self (s)
    1              0.000007     let l:lsp_id = s:servers[a:server_name]['lsp_id']
    1              0.000007     let l:data = copy(a:data)
    1              0.000004     if has_key(l:data, 'on_notification')
                                    let l:data['on_notification'] = '---funcref---'
    1              0.000001     endif
    1   0.000055   0.000017     call lsp#log_verbose('--->', l:lsp_id, a:server_name, l:data)
    1   0.000468   0.000016     return lsp#client#send_request(l:lsp_id, a:data)

FUNCTION  <SNR>146_on_stdout()
    Defined: ~/.config/nvim/pack/packager/start/vim-lsp/autoload/lsp/client.vim:33
Called 13 times
Total time: 485.806689
 Self time: 423.528641

count  total (s)   self (s)
   13              0.000191     let l:ctx = get(s:clients, a:id, {})
                            
   13              0.000028     if empty(l:ctx)
                                    return
   13              0.000010     endif
                            
   13              0.000032     if empty(l:ctx['buffer'])
   13              0.035081         let l:ctx['buffer'] = join(a:data, "\n")
                                else
                                    let l:ctx['buffer'] .= join(a:data, "\n")
   13              0.000009     endif
                            
46990              0.027256     while 1
46990              0.071495         if l:ctx['content-length'] < 0
                                        " wait for all headers to arrive
46990             39.147711             let l:header_end_index = stridx(l:ctx['buffer'], "\r\n\r\n")
46990              0.079043             if l:header_end_index < 0
                                            " no headers found
   13              0.000011                 return
46977              0.022392             endif
46977             74.156108             let l:headers = l:ctx['buffer'][:l:header_end_index - 1]
46977   1.510106   0.512810             let l:ctx['content-length'] = s:get_content_length(l:headers)
46977              0.068845             if l:ctx['content-length'] < 0
                                            " invalid content-length
                                            call lsp#log('on_stdout', a:id, 'invalid content-length')
                                            call s:lsp_stop(a:id)
                                            return
46977              0.024649             endif
46977             78.044024             let l:ctx['buffer'] = l:ctx['buffer'][l:header_end_index + 4:] " 4 = len(\r\n\r\n)
46977              0.037674         endif
                            
46977             74.210136         if len(l:ctx['buffer']) < l:ctx['content-length']
                                        " incomplete message, wait for next buffer to arrive
                                        return
46977              0.023147         endif
                            
                                    " we have full message
46977             74.240047         let l:response_str = l:ctx['buffer'][:l:ctx['content-length'] - 1]
46977              0.103594         let l:ctx['content-length'] = -1
                            
46977              0.032400         try
46977              0.496530             let l:response = json_decode(l:response_str)
                                    catch
                                        call lsp#log('s:on_stdout json_decode failed', v:exception)
46977              0.032367         endtry
                            
46977             78.092663         let l:ctx['buffer'] = l:ctx['buffer'][len(l:response_str):]
                            
46977              0.121368         if exists('l:response')
                                        " call appropriate callbacks
46977              0.234840             let l:on_notification_data = { 'response': l:response }
46977              0.140506             if has_key(l:response, 'method') && has_key(l:response, 'id')
                                            " it is a request from a server
    1              0.000002                 let l:request = l:response
    1              0.000003                 if has_key(l:ctx['opts'], 'on_request')
    1   0.002083   0.000013                     call l:ctx['opts']['on_request'](a:id, l:request)
    1              0.000001                 endif
46976              0.077891             elseif has_key(l:response, 'id')
                                            " it is a request->response
    1              0.000007                 if !(type(l:response['id']) == type(0) || type(l:response['id']) == type(''))
                                                " response['id'] can be number | string | null based on the spec
                                                call lsp#log('invalid response id. ignoring message', l:response)
                                                continue
    1              0.000001                 endif
    1              0.000005                 if has_key(l:ctx['requests'], l:response['id'])
    1              0.000007                     let l:on_notification_data['request'] = l:ctx['requests'][l:response['id']]
    1              0.000001                 endif
    1              0.000004                 if has_key(l:ctx['opts'], 'on_notification')
                                                " call client's on_notification first
    1              0.000001                     try
    1   0.012686   0.000026                         call l:ctx['opts']['on_notification'](a:id, l:on_notification_data, 'on_notification')
                                                catch
                                                    call lsp#log('s:on_stdout client option on_notification() error', v:exception, v:throwpoint)
    1              0.000001                     endtry
    1              0.000000                 endif
    1              0.000005                 if has_key(l:ctx['on_notifications'], l:response['id'])
                                                " call lsp#client#send({ 'on_notification }) second
                                                try
                                                    call l:ctx['on_notifications'][l:response['id']](a:id, l:on_notification_data, 'on_notification')
                                                catch
                                                    call lsp#log('s:on_stdout client request on_notification() error', v:exception, v:throwpoint)
                                                endtry
                                                unlet l:ctx['on_notifications'][l:response['id']]
    1              0.000001                 endif
    1              0.000003                 if has_key(l:ctx['requests'], l:response['id'])
    1              0.000003                     unlet l:ctx['requests'][l:response['id']]
                                            else
                                                call lsp#log('cannot find the request corresponding to response: ', l:response)
    1              0.000000                 endif
46975              0.022651             else
                                            " it is a notification
46975              0.106727                 if has_key(l:ctx['opts'], 'on_notification')
46975              0.024123                     try
46975  61.845271   0.579250                         call l:ctx['opts']['on_notification'](a:id, l:on_notification_data, 'on_notification')
                                                catch
                                                    call lsp#log('s:on_stdout on_notification() error', v:exception, v:throwpoint)
46975              0.030780                     endtry
46975              0.020701                 endif
46977              0.018720             endif
46977              0.017681         endif
                            
46977              0.081976         if empty(l:response_str)
                                        " buffer is empty, wait for next message to arrive
                                        return
46977              0.019368         endif
46977              0.025323     endwhile
```

comparision here also seems to be slow `if l:Item == l:Sink`.

```
FUNCTION  <SNR>113_makeSubjectFactory()
    Defined: ~/.config/nvim/pack/packager/start/vim-lsp/autoload/lsp/callbag.vim:64
Called 46979 times
Total time:  56.726363
 Self time:  31.892247

count  total (s)   self (s)
46979              0.044260     if a:t == 0
                                    let l:Sink = a:d
                                    call add(a:data['sinks'], l:Sink)
                                    call l:Sink(0, function('s:makeSubjectSinkCallback', [a:data, l:Sink]))
46979              0.020205     else
46979              0.159126         let l:zinkz = copy(a:data['sinks'])
46979              0.051531         let l:i = 0
46979              0.086889         let l:n = len(l:zinkz)
328853              0.343285         while l:i < l:n
281874              0.515426             let l:Sink = l:zinkz[l:i]
281874              0.244410             let l:j = -1
281874              0.254500             let l:found = 0
281874              0.501847             for l:Item in a:data['sinks']
281874              0.284862                 let l:j += 1
281874             24.272767                 if l:Item == l:Sink
281874              0.366934                     let l:found = 1
281874              0.183016                     break
                                            endif
281874              0.182857             endfor
                            
281874              0.232140             if l:found
281874  27.129702   2.297715                 call l:Sink(a:t, a:d)
281874              0.122119             endif
281874              0.320553             let l:i += 1
328853              0.193220         endwhile
46979              0.019089     endif
``

There is another callback i need dig into.

```
FUNCTION  <SNR>113_shareSourceCallback()
    Defined: ~/.config/nvim/pack/packager/start/vim-lsp/autoload/lsp/callbag.vim:1379
Called 281874 times
Total time:  24.833525
 Self time:   5.771995

count  total (s)   self (s)
281874              0.325687     if a:t == 0
                                    let a:data['sourceTalkback'] = a:d
                                    call a:sink(0, a:data['talkback'])
281874              0.129105     else
563748              0.839128         for l:S in a:data['sinks']
281874  21.006636   1.946644             call l:S(a:t, a:d)
563748              0.300349         endfor
281874              0.116006     endif
281874              0.214631     if a:t == 2
                                    let a:data['sinks'] = []
281874              0.110423     endif
```

some filter condition also seems to be slow.

```
FUNCTION  <SNR>113_filterSourceCallback()
    Defined: ~/.config/nvim/pack/packager/start/vim-lsp/autoload/lsp/callbag.vim:447
Called 281908 times
Total time:  19.070193
 Self time:   7.222504

count  total (s)   self (s)
281908              0.252768     if a:t == 0
                                    let a:data['talkback'] = a:d
                                    call a:data['sink'](a:t, a:d)
281908              0.232699     elseif a:t == 1
281908   2.791766   1.325942         if a:data['condition'](a:d)
   35   0.005053   0.001666             call a:data['sink'](a:t, a:d)
281873              0.138869         else
281873  13.632243   3.259980             call a:data['talkback'](1, lsp#callbag#undefined())
281908              0.116945         endif
                                else
                                    call a:data['sink'](a:t, a:d)
281908              0.110193     endif
```


I haven't finished looking at all the logs. we need to figure out all the logs that have self time greater than 2sec and should be easy to find out.

```
Total time:  19.070193
 Self time:   7.222504
```

if you have an opensource large project that i can repro it on that would be great.

**Comment by hrsh7th** [comment] 2021-02-27 05:20
It's interesting.

@jbarik Could you provide minimal project for repro? I don't have large cpp code base.

**Comment by prabirshrestha** [comment] 2021-02-27 05:39
If the project is private we might even be able to repro this by how big the file is lines/cols/filesize. We could create a file like this and try it out.

```
void f1() {}
void f2() {}
....
void f100000000() {}
```

I have thought of converting the lsp client to lua in the future long time back but I think we can still make improvements vimscript implementation.

Things like this could be interesting if we can optimize it in vim.

```
46990             39.147711             let l:header_end_index = stridx(l:ctx['buffer'], "\r\n\r\n")
```

**Comment by hrsh7th** [comment] 2021-02-27 05:42
I'm worrying to the executed line has 46990 counts...

**Comment by prabirshrestha** [comment] 2021-02-27 05:46
ya. something seems to be wrong with the client.

```
46990              0.027256     while 1
46990              0.071495         if l:ctx['content-length'] < 0
                                        " wait for all headers to arrive
```

I'm wondering if we are getting too many messages from the server or if the messages are too large. I have noticed this with rust. https://github.com/rust-analyzer/rust-analyzer/issues/7590

**Comment by hrsh7th** [comment] 2021-02-27 06:08
Hm... I tried to use ccls with vim-lsp but this issue didn't occur.

@jbarik Please put the `lsp.log` if you can.

**Comment by jbarik** [comment] 2021-02-27 18:08
Thanks for looking into the issue. 

Unfortunately the code is proprietary. The file is not at all big. It has only 37 lines. The header includes <map> and one more class header(98 lines).

There is one more piece of information which might interest you. When I open this file in a freshly synced sandbox/repository, for the first time I don't see any issues. If I close neovim and open the same file(or any other file) then I see the issue.

I am attaching two vim-lsp log files. One when I don't see any issue and second with the issue.

[vim-lsp-no-issue.log](https://github.com/prabirshrestha/vim-lsp/files/6055034/vim-lsp-no-issue.log)
[vim-lsp-with-issue.log](https://github.com/prabirshrestha/vim-lsp/files/6055035/vim-lsp-with-issue.log)

When I use neovim's inbuilt lsp, I don't see the issue while starting neovim and opening a file. Neovim stays responsive. But I start seeing another issue(which I don't see when I use vim-lsp) i.e. every now and then ccls goes into overdrive and consumes lot of cpu and memory. I am yet to find exactly what operation in neovim pushes ccls into overdrive mode, but I guess if I open a new file or start querying ccls for definition etc. it starts using lot of cpu power.

I tried turning on ccls's log files but something went wrong - lsp queries from neovim broke. It didn't even start ccls. I'll keep trying to get ccls log.

**Comment by prabirshrestha** [comment] 2021-02-27 20:01
Seems like it is the same issue as I posted for rust analyzer. You are getting too many $/progress messages and unfortunately vim script is slow. I would suggest to disable the work done progress and see if that works. Server should respect the flag. Also feel free to file a bug on server to throttle the progress events.

**Comment by jbarik** [comment] 2021-02-28 07:08
I am not sure how to disable work-done-progress. I don't find anything in ccls documents. How should I pass that flag?

Also any idea why this issue doesn't show up for the first time?

Thanks

**Comment by jbarik** [comment] 2021-02-28 07:11
Oh, I see that flag in vim-lsp document. I'll try that.

**Comment by prabirshrestha** [comment] 2021-02-28 20:31
It is here - https://github.com/prabirshrestha/vim-lsp/blob/master/autoload/lsp.vim#L544-L546

Server also needs to respect the flag. `let g:lsp_work_done_progress_enabled=0`

**Comment by jbarik** [comment] 2021-03-02 04:44
I set that flag(let g:lsp_work_done_progress_enabled=0) but it didn't help. Also isn't that flag disabled by default? 

Maybe as you said, the server didn't respect that flag.

**Comment by prabirshrestha** [comment] 2021-03-02 04:59
Feel free to add add link once it is disabled.

In the meantime I created a bug here https://github.com/MaskRay/ccls/issues/772

**Comment by prabirshrestha** [comment] 2021-03-08 02:35
I stated porting lsp client to lua for neovim using libuv that comes as part of `vim.loop` in neovim but hit an issue where funcrefs are not auto translating from vimscript to lua world so stuck there.  https://github.com/neovim/neovim/issues/12537#issuecomment-792417591

I'm playing with this branch. https://github.com/prabirshrestha/vim-lsp/tree/lua-lsp-client. I have only got the server to start and send requests as well as parse response but since I don't get funcrefs from vimscript I can't notify back to the vimscript world.

**Comment by prabirshrestha** [comment] 2021-03-09 03:22
Sent a PR to vim to add support for passing vimscript lambdas to lua and is now merged to master. https://github.com/vim/vim/commit/86c3a2162c2e78b4f0b87b47779cc1452990ee1b. Neovim would need some similar patches. 

I was really hoping to build on neovim first since I could use `libuv` from lua and stay in the lua world as much as possbile but now I need to first add support for `spawn` in lua callbag to support vim jobs similar to libuv. https://github.com/prabirshrestha/lua-callbag/pull/13

I also looked at neovim's lsp parser and seems like they do an interesting trick by using arrays instead of string concat to avoid resizing strings when concatenating buffer string to avoid string allocation so that trick could be ported to to vim-lsp. https://github.com/neovim/neovim/blob/7c204af87aa74120a70db14b87c5e7c7096ae478/runtime/lua/vim/lsp/rpc.lua#L158-L160 On the down side neovim's implementation does seem to be going back and forth on vimscript and lua more often than I would like.

**Comment by prabirshrestha** [comment] 2021-03-12 18:01
seems like throttling ccls is already fixed. https://github.com/MaskRay/ccls/issues/772#issuecomment-797577617

**Comment by hrsh7th** [comment] 2021-03-21 06:46
I've implemented the avoiding string concatenation in vim-vital-vs but I don't know if it improves perf or not and my implementation wrong or not.

https://github.com/hrsh7th/vim-vital-vs/commit/6af4d3483e5e33d881f9d6da8c766d4bc9b43bf8

**Comment by prabirshrestha** [comment] 2021-03-21 18:42
Another small perf improvement in async.vim https://github.com/prabirshrestha/vim-lsp/pull/1117

@hrsh7th I'm wondering if we can also remove the dict looks as much as possible and use lists instead state = `[headers, contentlength, buffers]`.

My hope is to use [callbag.vim's spawn](https://github.com/prabirshrestha/callbag.vim/pull/18) instead of [async.vim](https://github.com/prabirshrestha/async.vim) so one thing that would be very interesting is if vim-vital-vs could have a rpc parser that is standalone and could be used based on any job implementation. For example in neovim we could use libuv loop. `callbag#spawn` is also smaller code than async.vim and has lot more perf improvements that I learnt from async.vim.

**Comment by prabirshrestha** [comment] 2021-03-22 02:06
@jbarik can you run `ccls --version` and let me know which version you are using.

@hrsh7th another option would be to create a custom server and just spam the client. Might be can modify https://github.com/theia-ide/typescript-language-server.

**Comment by jbarik** [comment] 2021-03-22 12:30
For some reason, I'm not getting the version for ccls

![Screenshot from 2021-03-22 17-58-33](https://user-images.githubusercontent.com/22386546/111990002-7efef680-8b38-11eb-946d-a3809174f8f8.png)

**Comment by bleskodev** [comment] 2021-04-25 14:45
Hi, first of all, I would like to thank you for your work on this great plugin. It is really appreciated!

I have recently stumbled on another bottleneck when opening bigger 'c' files: it seems related to folding code. 
Here is the profile log: 
[vimprofile.log](https://github.com/prabirshrestha/vim-lsp/files/6372167/vimprofile.log)

I'm opening a .c file with 15k loc.
To (hopefully) reproduce the same behavior download this version of Mongoose web server (https://github.com/cesanta/mongoose/releases/tag/6.7) and open mongoose.c file. 
I'm using vim 8.2, with vim-lsp and ccls as a backend LSP server.

I can also say that the behaviour I see is exactly the same as described in #786 (vim blocked for ~60s, first 10s with cursor blinking, after that even cursor stops blinking and in the end the message: 'redrawtime exceeded syntax highlighting disabled' followed by vim finally reacting to the input).

I hope this can help you make this plugin even better!

**Comment by prabirshrestha** [comment] 2021-05-29 06:37
Please try [parse-array-perf](https://github.com/prabirshrestha/vim-lsp/tree/parse-array-perf) which now uses array instead of string concat to parse as is based on vim-vital-vs algorithm.

When I had work done progress enabled for a rust, I was able to see significant improvements with the editor being responsive compared to one without this patch.

**Closed** 2021-05-30 20:17 UTC
Labels: enhancement, perf

**Comment by prabirshrestha** [comment] 2021-05-30 20:20
Please try in master. It should be lot faster with parsing array directly in the client instead of concatenating with string and searching across large string.

@bleskodev for foldexpr please file another issue so we can track it separately.
