### ISSUE TITLE
Tab completion inserts type into buffer

### ISSUE THREAD

**Issue by ElArtista** [prabirshrestha/vim-lsp#328] opened 2019-03-02 15:09 UTC
I have the given bindings for tab completion:

```
" Tab completion
imap <c-space> <Plug>(asyncomplete_force_refresh)
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>\<cr>" : "\<cr>"
autocmd! CompleteDone * if pumvisible() == 0 | pclose | endif
```

When i try to use tab to complete with what i see in the popup menu, using vim-lsp and ccls as the language server, vim inserts also the type into the buffer like this:

![image](https://user-images.githubusercontent.com/4622346/53683770-50bddc80-3d0d-11e9-9b9c-f0b90c34ce7f.png)

What can we do to fix this? Is this a vim-lsp or an asyncomplete.vim problem?

**Comment by mattn** [comment] 2019-03-02 15:43
Where is the location you started completion?

```
sp_params.
```
Did you start completion at here? Could you please provide log file?

**Comment by ElArtista** [comment] 2019-03-03 10:44
Yep i started the completion there. What log files do you need? The vim-lsp one, or the ccls (language server) one?

**Comment by prabirshrestha** [comment] 2019-03-03 19:37
vim-lsp should be good.

**Comment by prabirshrestha** [comment] 2019-03-05 16:47
Also give v2 asyncomolete branch a try

**Comment by ElArtista** [comment] 2019-03-05 19:45
Tried asyncomplete v2 branch, same thing.
Just made a minimal project setup, info bellow:

![image](https://user-images.githubusercontent.com/4622346/53832779-b7eac380-3f8f-11e9-9d26-925228d8ee53.png)

Completion started at `f.x`.

Logs bellow:

[vim-lsp.log](https://github.com/prabirshrestha/vim-lsp/files/2932545/vim-lsp.log)
[asyncomplete.log](https://github.com/prabirshrestha/vim-lsp/files/2932546/asyncomplete.log)
[ccls.log](https://github.com/prabirshrestha/vim-lsp/files/2932548/ccls.log)

**Comment by prabirshrestha** [comment] 2019-03-05 20:36
Can you file the bug in asyncomplete.vim instead. Also would be good to have a minimal vimrc with a same repo.

**Comment by ElArtista** [comment] 2019-03-05 20:38
You want some test repo to reproduce it yourself?

**Comment by prabirshrestha** [comment] 2019-03-05 20:39
Yes. I would like to try it out when I'm free .

**Comment by ElArtista** [comment] 2019-03-05 20:40
Ok, i'll make you a C test repository with a minimal .vimrc to go with it.
Shall you transfer the issue to the asyncomplete repo like this? https://help.github.com/en/articles/transferring-an-issue-to-another-repository

**Comment by ElArtista** [comment] 2019-03-11 18:49
Just found out it was an issue with the `completion.detailedLabel` option having a default of true in ccls.
Leaving it here in case any other one is interested.

**Comment by bfrg** [comment] 2019-03-16 22:13
I'm having the same issue. It doesn't matter whether I have set `omnifunc=lsp#complete` or use the `asyncomplete.vim` plugin.

I tried it with [vim-lsc](https://github.com/natebosch/vim-lsc) and it works out of the box.
In either case I didn't set the `completion.detailedLabel` option.

### Screenshots
![screenshot-2019-03-16_215104](https://user-images.githubusercontent.com/6266600/54482023-12f8a200-483d-11e9-82f2-30a4e8e6998d.png)
![screenshot-2019-03-16_215112](https://user-images.githubusercontent.com/6266600/54482024-1724bf80-483d-11e9-8a92-2c02fc51935d.png)

### How to reproduce the issue
```bash
$ mkdir -p minimal minimal/build
$ touch CMakeLists.txt minimal.cpp
```
`minimal.cpp` file:
```cpp
#include <iostream>

int main() {
    std::cou
    //     ^ trigger completion here
}
```
`CMakeLists.txt` file:
```cmake
project(minimal)

# Generate compile_commands.json by default
set(CMAKE_EXPORT_COMPILE_COMMANDS "ON"
    CACHE BOOL
    "Enable/Disable output of compile commands during generation."
    FORCE)

add_executable(minimal "minimal.cpp")
```
`vimrc` configuration:
```vim
augroup vimrc_lsp
    autocmd!
    if executable('ccls')
        autocmd User lsp_setup call lsp#register_server({
                \ 'name': 'ccls',
                \ 'cmd': {server_info->['ccls']},
                \ 'root_uri': {server_info->lsp#utils#path_to_uri(
                \                               lsp#utils#find_nearest_parent_file_directory(
                \                                   lsp#utils#get_buffer_path(),
                \                                   'compile_commands.json'))},
                \ 'initialization_options': {
                \    'cache': {'directory': '/tmp/ccls_cache'},
                \    'diagnostics': { 'onChange': 200 },
                \ },
                \ 'whitelist': ['c', 'cpp'],
                \ })
        autocmd FileType c,cpp,cuda setlocal omnifunc=lsp#complete
    endif
augroup END
```
```bash
$ cd minimal/build/
$ cmake ..
$ cd ..
$ ln -s build/compile_commands.json compile_commands.json
```

**Comment by ElArtista** [comment] 2019-03-17 17:20
Relevant `ccls` issue and answer:
https://github.com/MaskRay/ccls/issues/318

**Comment by prabirshrestha** [comment] 2019-03-17 17:31
Can you try this?

https://github.com/prabirshrestha/vim-lsp/pull/344

There was a spelling mistake.

**Comment by ElArtista** [comment] 2019-03-17 17:39
I just tried it, no luck. If don't put ` 'completion': {'detailedLabel': v:false}` in the initializationOptions it works as presented above.

**Comment by bfrg** [comment] 2019-03-17 18:11
@prabirshrestha  vim-lsp needs `textEdit` for this to work, see PR #318.

According to [LSP specifications](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion), `insertText` is deprecated and `textEdit` should be used instead.

**Comment by prabirshrestha** [comment] 2019-03-17 18:12
What about this PR? https://github.com/prabirshrestha/vim-lsp/pull/318

It adds support for TextEdit for omni.

**Comment by ElArtista** [comment] 2019-03-17 20:41
Yep, tried both checking out PR #318 + applying the change in PR #344, still the same.

**Comment by bfrg** [comment] 2019-03-17 22:00
I just tested PR #318 and it works only partially. If you cycle through the completion items with `<c-n>` or `<c-p>`, vim-lsp will insert the full item (including the type of the variable, full function signature, or template parameters). However if you explicitly accept the item by pressing `<c-y>` while the popup menu is still visible (see `:help complete_CTRL-Y`), all that unnecessary text will be deleted.

So in its current state, it works fine only if you cycle through the completion items with arrow `<up>` and `<down>` keys and select the item with `<enter>`.

**Comment by ElArtista** [comment] 2019-03-17 22:30
Yep I can also confirm what @bfrg is saying, just note that <c-y> will insert only the correct portion of the completion, while <enter> will also enter a newline too.

**Comment by bfrg** [comment] 2019-03-17 22:45
@ElArtista Vim entered the additional newline because you probably cycled through the items with `<c-n>` or `<c-p>` which instantly inserts the item, and afterwards you accepted the item with `<enter>`. Note that `<c-n>` and arrow `<down>` key are not the same, see `:help popupmenu-keys`.

**Comment by prabirshrestha** [comment] 2019-03-17 23:06
I think the best solution here is to totally ignore insertText and use TextEdit only.

**Comment by prabirshrestha** [comment] 2019-03-17 23:09
Can you try disabling insert text by setting  g:lsp_insert_text_enabled to 0.

**Comment by bfrg** [comment] 2019-03-18 00:10
`let g:lsp_insert_text_enabled = 0` doesn't help. The full item is still inserted on pressing `<c-n>` or `<c-p>`.

**Comment by prabirshrestha** [comment] 2019-05-15 13:07
@ElArtista can you paste one of the completion item for ccls.

So I did find the issue here. Here is one of the completion item from golang.

```json
{
    "label": "Errorf(format string, a ...interface{})",
    "insertTextFormat": 1,
    "preselect": true,
    "sortText": "00000",
    "kind": 3,
    "filterText": "Errorf",
    "textEdit": {
      "range": {
        "end": {
          "character": 8,
          "line": 34
        },
        "start": {
          "character": 8,
          "line": 34
        }
      },
      "newText": "Errorf"
    },
    "command": {
      "title": "",
      "command": "editor.action.triggerParameterHints"
    },
    "detail": "error"
}
```

We currently show label in pum. If filter text we should show that instead of label in case of golang. But from docs:
https://microsoft.github.io/language-server-protocol/specification#textDocument_completion, seems like vim-lsp is behaving correctly.

```
interface CompletionItem {
	/**
	 * The label of this completion item. By default
	 * also the text that is inserted when selecting
	 * this completion.
	 */
	label: string;

	/**
	 * A string that should be used when filtering a set of
	 * completion items. When `falsy` the label is used.
	 */
	filterText?: string;
}
```

but now the problem is if we don't display the label, `textEdit` will be invalid.

Currently we only call `s:apply_text_edits()` when `CompleteDone` is called. Seems like we need to also apply the text edits when `CompleteChanged` is called. `CompleteChanged` doesn't exist in older vim and neovim so they will still have this impact.

**Comment by tsufeki** [comment] 2019-05-15 19:52
@prabirshrestha I don't know that much about vim's completion. Won't editing close the menu? Will undoing previous item's edit be required?

Another approach may be to avoid _all_ changes to the buffer when pum is open (i.e. set `'word': ''`, use `'abbr'` for label and ignore `CompleteChanged`), and only apply edits on `CompleteDone`. This is drastically different from what we vim users are used to though.

> but now the problem is if we don't display the label, `textEdit` will be invalid.

What do you mean by "invalid"?

**Comment by ElArtista** [comment] 2019-05-18 10:30
@prabirshrestha I updated to the latest vim-lsp version and tried completion without the `completion.detailedLabel` ccls option as stated above and got the same result..

Here is the completion item:

```
{  
   "label":"x : int",
   "insertTextFormat":1,
   "sortText":"   !",
   "kind":5,
   "filterText":"x",
   "textEdit":{  
      "range":{  
         "end":{  
            "character":6,
            "line":44
         },
         "start":{  
            "character":6,
            "line":44
         }
      },
      "newText":"x"
   },
   "detail":"foo"
}
```

**Comment by prabirshrestha** [comment] 2019-05-19 07:09
vim-lsc seems to be doing this i.e. they seems to be using it as a word while vim-lsp applies the text edit at the end.

```vim
 `word` suggestions are taken from the highest priority field according to
" order `textEdit` > `insertText` > `label`.
" `label` is always expected to be set and is used as the `abbr` shown in the
" popupmenu. This may be different from the inserted text.
function! s:CompletionItem(completion_item) abort
  let item = {'abbr': a:completion_item.label, 'icase': 1, 'dup': 1}
  if has_key(a:completion_item, 'textEdit')
      \ && type(a:completion_item.textEdit) == v:t_dict
      \ && has_key(a:completion_item.textEdit, 'newText')
    let item.word = a:completion_item.textEdit.newText
    let item.start_col = a:completion_item.textEdit.range.start.character + 1
```

**Comment by bfrg** [comment] 2019-11-19 02:33
`ccls` added a new option [completion.detailedLabel](https://github.com/MaskRay/ccls/wiki/Customization#completiondetailedlabel). If you set it to `false`, vim-lsp won't insert the type anymore.

The following works on my system:
```vim
let s:findjson = {... -> fnamemodify(findfile('compile_commands.json', expand('%:p') . ';'), ':p:h')}

augroup lsprc
    autocmd!
    if executable('ccls')
        autocmd User lsp_setup call lsp#register_server(#{
                \   name: 'ccls',
                \   cmd: {... -> ['ccls']},
                \   whitelist: ['c', 'cpp', 'objc', 'objcpp'],
                \   root_uri: s:findjson,
                \   initialization_options: #{
                \      cache: #{directory : '/tmp/ccls_cache/cache'},
                \      completion: #{detailedLabel: v:false}
                \   }
                \ })
    endif
augroup END
```

**Comment by prabirshrestha** [comment] 2019-12-26 05:42
closing stale issue.

**Closed by prabirshrestha** 2019-12-26 05:42 UTC
