### ISSUE TITLE
Invalid arguments, 83_place_highlights

### ISSUE THREAD

**Issue by DanielViberg** [prabirshrestha/vim-lsp#1454] opened 2023-04-04 08:59 UTC
Running:
intelephense: running
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Mar 23 2023 11:08:11)

```
Error detected while processing function <SNR>76_debounceTimeTimerCallback[1]..<SNR>76_tapSourceCallback[4]..<SNR>76_tapSourceCallback[1]..<lambda>38[1]..<SNR>83_set_highlights[10]..<SNR>83_place_highlights:
line   59:
E684: List index out of range: 0
Error detected while processing function <SNR>76_debounceTimeTimerCallback[1]..<SNR>76_tapSourceCallback[4]..<SNR>76_tapSourceCallback[1]..<lambda>38[1]..<SNR>83_set_highlights[10]..<SNR>83_place_highlights:
line   59:
E116: Invalid arguments for function strlen(getbufline(a:bufnr, l:line, l:line)[0]) + 1
```

**Comment by sullivan-sean** [comment] 2023-08-18 04:28
I'm also encountering this same issue, any ideas what is going on here?

**Comment by jbarik** [comment] 2023-09-27 12:15
I am encountering this issue as soon as I open a *.norg file.

**Comment by jbarik** [comment] 2023-10-06 08:15
In my case, I got around the issue by adding 'norg' file to the blocklist during lsp registration.

**Comment by jbarik** [comment] 2023-10-09 10:38
This issue looks like a duplicate of the issue fixed by : https://github.com/prabirshrestha/vim-lsp/pull/1481

**Comment by prabirshrestha** [comment] 2024-02-25 11:11
Closing as fixed. Please ping if you are still having issues.

**Closed by prabirshrestha** 2024-02-25 11:11 UTC
