### ISSUE TITLE
vim-lsp hides vim's empty-buffer welcome message

### ISSUE THREAD

**Issue by flwyd** [prabirshrestha/vim-lsp#1057] opened 2021-01-25 05:24 UTC
When running `vim` with no arguments, vim-lsp causes the "Welcome message" in the empty buffer to disappear after a second or so.  (The welcome message says the vim version, Bram's name, the availability of `:help`, Uganda info, etc.)  This message typically stays around until the buffer is modified or the window is redrawn.  It would be nice to not clear this message without the user taking action, since it's a convenient way to check the vim version.

I've seen this behavior on version 8.1.2269, 8.2.2164, 8.2.1719, and 8.0.1365. I isolated vim-lsp as the cause by running `vim -u` with the following minimal vimrc:
```vim
set nocp
filetype plugin indent on
set rtp+=~/.vim/plugged/vim-lsp
```

**Comment by JacksonGariety** [comment] 2021-01-30 06:33
I am also experiencing this issue and would like it to stop.

**Comment by rhysd** [comment] 2021-04-04 12:38
Is this issue still happening?

**Comment by rhysd** [comment] 2021-04-04 12:51
I tried this but it did not reproduce in my environment with Vim 8.2.2576.

![tmp](https://user-images.githubusercontent.com/823277/113509302-ca30f480-958f-11eb-87e8-a4a0bb119e20.gif)

**Comment by prabirshrestha** [comment] 2021-04-04 15:30
I fixed it for vim but not for neovim. I could find why neovim clears. For vim it was due to prop clear.

**Comment by rhysd** [comment] 2021-04-04 15:45
@prabirshrestha I also tried neovim, but it also did not clear the welcome message. Do you remember what version of Neovim you tried?

![tmp](https://user-images.githubusercontent.com/823277/113514193-34ee2a00-95a8-11eb-863e-64867d021891.gif)

**Comment by prabirshrestha** [comment] 2021-04-04 16:03
It was neovim head.

**Comment by rhysd** [comment] 2021-04-05 06:56
OK, I'll try 0.5 HEAD tonight.

**Comment by rhysd** [comment] 2021-04-05 11:06
I tried this with latest Neovim HEAD (`v0.5.0-dev+nightly`) but it did not reproduce.

**Comment by rhysd** [comment] 2021-04-12 09:11
This seems no longer happening on the latest Vim and Neovim. Closing.

**Closed by rhysd** 2021-04-12 09:11 UTC
